name: foodbank
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter   
  intl: ^0.17.0
  go_router: ^5.1.5
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.2.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  generate: true

  
  assets:
    - assets/images/logo.png
    - assets/images/screen-picture.png
    - assets/images/hamburger.png
    
 
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
       
